export const COMPATIBILITY_MATRIX = [
    { a: "Mechanics", b: "Structures", status: "S", rule: "moving loads, joints, stress, breakage" },
    { a: "Mechanics", b: "Electricity", status: "S", rule: "motors and generators transfer between electrical/mechanical domains" },
    { a: "Mechanics", b: "Magnetism", status: "S", rule: "magnetic forces act on tagged physical bodies" },
    { a: "Mechanics", b: "Water", status: "S", rule: "pumps/water wheels/mechanical outputs" },
    { a: "Mechanics", b: "Flight/Air", status: "S", rule: "thrust, fans, moving bodies" },
    { a: "Mechanics", b: "Logic", status: "S", rule: "sensors and actuators control mechanisms" },
    { a: "Structures", b: "Electricity", status: "P", rule: "electrical objects mount physically; structure itself is not a general circuit conductor" },
    { a: "Structures", b: "Magnetism", status: "S", rule: "magnetic forces can load/move attached structures" },
    { a: "Structures", b: "Water", status: "P", rule: "pipe systems mount to structures; erosion is not simulated" },
    { a: "Structures", b: "Flight/Air", status: "S", rule: "wind/thrust can load structures" },
    { a: "Structures", b: "Logic", status: "P", rule: "logic hardware attaches physically; no special structural computation" },
    { a: "Electricity", b: "Magnetism", status: "S", rule: "electromagnets and magnetic switches" },
    { a: "Electricity", b: "Water", status: "D", rule: "no general shock/short-circuit simulation in 1.0; authored content avoids teaching from water/electric contact" },
    { a: "Electricity", b: "Flight/Air", status: "S", rule: "powered fans/propellers" },
    { a: "Electricity", b: "Logic", status: "S", rule: "sensors/controllers/actuators" },
    { a: "Magnetism", b: "Water", status: "P", rule: "both may coexist; no special water-magnet rule" },
    { a: "Magnetism", b: "Flight/Air", status: "P", rule: "generic body forces only; no dedicated aerodynamic-magnetic coupling" },
    { a: "Magnetism", b: "Logic", status: "S", rule: "magnetic switches/sensors can emit logic events" },
    { a: "Water", b: "Flight/Air", status: "P", rule: "both may coexist; no fluid-dynamics aircraft model" },
    { a: "Water", b: "Logic", status: "S", rule: "logic may control pumps, valves, sensors" },
    { a: "Flight/Air", b: "Logic", status: "S", rule: "logic may control fans, propellers, boosters" },
    { a: "Materials/Environment", b: "Mechanics", status: "S", rule: "mass, friction, bounce, gravity, wind" },
    { a: "Materials/Environment", b: "Structures", status: "S", rule: "strength/mass/grip presets" },
    { a: "Materials/Environment", b: "Magnetism", status: "S", rule: "magnetic-material tags" },
    { a: "Materials/Environment", b: "Flight/Air", status: "S", rule: "gravity/wind modifiers" },
    { a: "Materials/Environment", b: "Logic", status: "S", rule: "sensors may read supported tags/regions" }
];
export function compatibility(a, b) { return COMPATIBILITY_MATRIX.find(e => (e.a === a && e.b === b) || (e.a === b && e.b === a)); }
