export const REWARDS = [
    // parts (Free Build tray) — Motion starter set comes from the opening
    { id: "part.motion.roller", kind: "PART", title: "Roller", icon: "⚪", description: "A free-spinning roller for your builds." },
    { id: "part.motion.friction-high", kind: "PART", title: "Grip Pad", icon: "🟫", description: "A grippy surface that slows sliding." },
    { id: "part.motion.friction-low", kind: "PART", title: "Slide Pad", icon: "🧊", description: "A slippery surface for fast slides." },
    { id: "part.motion.bounce-pad", kind: "PART", title: "Bounce Pad", icon: "🟣", description: "A springy pad that bounces things back up." },
    { id: "part.motion.axle", kind: "PART", title: "Axle", icon: "➖", description: "Joins wheels to carts and frames." },
    // tools
    { id: "tool.force-scanner", kind: "TOOL", title: "Force Scanner", icon: "🔍", description: "Shows the pushes and pulls on moving things — now in Free Build too." },
    // stickers
    { id: "sticker.first-roll", kind: "STICKER", title: "First Roll", icon: "🎱", description: "You rolled a ball into the bucket." },
    { id: "sticker.safe-landing", kind: "STICKER", title: "Safe Landing", icon: "🪂", description: "Bolt got down gently." },
    { id: "sticker.brake-master", kind: "STICKER", title: "Brake Master", icon: "🛑", description: "You slowed a speeding cart." },
    { id: "sticker.special-delivery", kind: "STICKER", title: "Special Delivery", icon: "📦", description: "A parcel, launched by spring." },
    { id: "sticker.slip-n-grip", kind: "STICKER", title: "Slip & Grip", icon: "🧦", description: "You crossed grippy and slippy ground." },
    { id: "sticker.boing", kind: "STICKER", title: "Boing!", icon: "🦘", description: "A bounce hit the switch." },
    { id: "sticker.heavy-light", kind: "STICKER", title: "Heavy & Light", icon: "⚖️", description: "Same push, different results." },
    { id: "sticker.far-out", kind: "STICKER", title: "Far Out", icon: "📏", description: "Your cart went the distance." },
    { id: "sticker.scientist", kind: "STICKER", title: "Fair Test", icon: "🧪", description: "You compared two ramps fairly." },
    // badges
    { id: "badge.motion-yard", kind: "BADGE", title: "Motion Yard Restored", icon: "🏅", description: "The Motion Yard is running again!" },
    { id: "badge.mega-marble", kind: "BADGE", title: "Marble Mover", icon: "🔵", description: "You built the Giant Marble Delivery Machine." },
    // cosmetics
    { id: "avatar.hard-hat", kind: "AVATAR", title: "Hard Hat", icon: "⛑️", description: "Safety first, inventor.", piece: "inv.hat.hard-hat" },
    { id: "avatar.goggles", kind: "AVATAR", title: "Lab Goggles", icon: "🥽", description: "For serious experiments.", piece: "inv.glasses.goggles" },
    { id: "avatar.cap", kind: "AVATAR", title: "Speedy Cap", icon: "🧢", description: "Goes great with fast carts.", piece: "inv.hat.cap" },
    { id: "bolt.racing-stripes", kind: "BOLT_COSTUME", title: "Racing Stripes", icon: "🏁", description: "Bolt feels 12% faster. (Bolt is not faster.)" },
    { id: "bolt.duck-floatie", kind: "BOLT_COSTUME", title: "Duck Floatie", icon: "🦆", description: "Bolt is ready for bath time." },
    { id: "sprocket.bandana", kind: "SPROCKET_ACCESSORY", title: "Rescue Bandana", icon: "🧣", description: "Sprocket helped stop the runaway cart. Sort of." },
    { id: "sprocket.spring-collar", kind: "SPROCKET_ACCESSORY", title: "Spring Collar", icon: "🌀", description: "Boing-boing." },
    // workshop props + frames
    { id: "prop.bath-tub", kind: "PROP", title: "Giant Bath Tub", icon: "🛁", description: "The Duck Cannon target, now in your workshop." },
    { id: "prop.test-flag", kind: "PROP", title: "Test Track Flag", icon: "🚩", description: "Flies over the test track." },
    { id: "frame.wood", kind: "FRAME", title: "Wooden Frame", icon: "🖼️", description: "A frame for your invention shelf." },
    { id: "frame.gold", kind: "FRAME", title: "Golden Frame", icon: "🌟", description: "For your finest inventions." },
    { id: "prop.rubber-duck", kind: "PROP", title: "Champion Rubber Duck", icon: "🐤", description: "It has seen things. Mostly bathwater." },
    { id: "sticker.postie-thanks", kind: "STICKER", title: "Special Thanks", icon: "💌", description: "A thank-you from the campus post room." },
    // Science Fairs (M28): a ribbon for taking part in each fair (every accepted entry earns it — it is not a prize for winning).
    { id: "sticker.fair-1", kind: "STICKER", title: "Motion Makers Ribbon", icon: "🎗️", description: "You entered Science Fair 1." },
    { id: "sticker.fair-2", kind: "STICKER", title: "Strong & Powered Ribbon", icon: "🎗️", description: "You entered Science Fair 2." },
    { id: "sticker.fair-3", kind: "STICKER", title: "Water & Air Show Ribbon", icon: "🎗️", description: "You entered Science Fair 3." },
    { id: "sticker.fair-4", kind: "STICKER", title: "Smart Machines Ribbon", icon: "🎗️", description: "You entered Science Fair 4." },
    { id: "sticker.fair-5", kind: "STICKER", title: "Anything Goes Ribbon", icon: "🎗️", description: "You entered Science Fair 5." },
    // Inventor Contracts (M27): one thank-you sticker from each visitor.
    { id: "sticker.visitor-chef", kind: "STICKER", title: "Kitchen Helper", icon: "🍎", description: "Chef Pepper says thank you!" },
    { id: "sticker.visitor-builder", kind: "STICKER", title: "Crew Member", icon: "👷", description: "Builder Brick says thank you!" },
    { id: "sticker.visitor-farmer", kind: "STICKER", title: "Harvest Helper", icon: "🌽", description: "Farmer Fern says thank you!" },
    { id: "sticker.visitor-firefighter", kind: "STICKER", title: "Rescue Ready", icon: "🚒", description: "Captain Blaze says thank you!" },
    { id: "sticker.visitor-delivery", kind: "STICKER", title: "Speedy Delivery", icon: "🚚", description: "Dash the Driver says thank you!" },
    { id: "sticker.visitor-astronaut", kind: "STICKER", title: "Moon Crew", icon: "🛰️", description: "Astro Nova says thank you!" },
    { id: "sticker.visitor-zookeeper", kind: "STICKER", title: "Animal Friend", icon: "🦒", description: "Keeper Kiwi says thank you!" },
    { id: "sticker.visitor-pirate", kind: "STICKER", title: "Treasure Hunter", icon: "🏴‍☠️", description: "Captain Barnacle says thank you!" },
    { id: "sticker.visitor-musician", kind: "STICKER", title: "Encore!", icon: "🎵", description: "Maestro Tempo says thank you!" },
    { id: "sticker.visitor-park", kind: "STICKER", title: "Park Hero", icon: "🎠", description: "Ranger Rosa says thank you!" },
    { id: "sticker.visitor-mechanic", kind: "STICKER", title: "Fix-It Pro", icon: "🔧", description: "Wrench Wilma says thank you!" },
    { id: "sticker.visitor-scientist", kind: "STICKER", title: "Lab Partner", icon: "🔬", description: "Professor Quark says thank you!" },
    // Gear Garage (M12)
    { id: "part.gear.small", kind: "PART", title: "Small Gear", icon: "⚙️", description: "A little gear: spins fast." },
    { id: "part.gear.medium", kind: "PART", title: "Medium Gear", icon: "⚙️", description: "A middle-sized gear." },
    { id: "part.gear.large", kind: "PART", title: "Large Gear", icon: "⚙️", description: "A big gear: slow and strong." },
    { id: "part.gear.crank", kind: "PART", title: "Hand Crank", icon: "🔄", description: "Turn it and the gears go round." },
    { id: "part.gear.motor", kind: "PART", title: "Gear Motor", icon: "⚡", description: "A little motor that turns gears for you." },
    { id: "part.gear.belt-pulley", kind: "PART", title: "Pulley", icon: "⭕", description: "Pulleys share a belt and turn the same way." },
    { id: "part.gear.belt-pulley-big", kind: "PART", title: "Big Pulley", icon: "⭕", description: "A big pulley for slow, strong belts." },
    { id: "tool.spin-scanner", kind: "TOOL", title: "Spin Scanner", icon: "🌀", description: "Shows which way and how fast every gear turns — now in Free Build too." },
    { id: "sticker.door-opener", kind: "STICKER", title: "Door Opener", icon: "🚪", description: "You turned the stuck door." },
    { id: "sticker.wrong-way", kind: "STICKER", title: "Wrong Way Round", icon: "🔃", description: "You flipped the direction." },
    { id: "sticker.speedy-spin", kind: "STICKER", title: "Speedy Spin", icon: "💨", description: "Big gear, small gear, FAST fan." },
    { id: "sticker.strongman", kind: "STICKER", title: "Strong & Slow", icon: "🏋️", description: "You traded speed for strength." },
    { id: "sticker.going-up", kind: "STICKER", title: "Going Up!", icon: "🛗", description: "Bolt reached the top shelf." },
    { id: "sticker.triple-breeze", kind: "STICKER", title: "Triple Breeze", icon: "🌬️", description: "Three fans, one crank." },
    { id: "sticker.clock-fixer", kind: "STICKER", title: "Clock Fixer", icon: "🕰️", description: "The campus clock ticks again." },
    { id: "sticker.conveyor", kind: "STICKER", title: "Special Delivery Belt", icon: "📦", description: "The old conveyor rolls again." },
    { id: "sticker.gear-scientist", kind: "STICKER", title: "Gear Scientist", icon: "🔬", description: "You compared big and small gears fairly." },
    { id: "badge.clockwork-carnival", kind: "BADGE", title: "Carnival Restorer", icon: "🎠", description: "The Clockwork Carnival runs again!" },
    { id: "badge.gear-garage", kind: "BADGE", title: "Gear Garage Restored", icon: "🏅", description: "The Gear Garage is turning again!" },
    { id: "bolt.top-hat", kind: "BOLT_COSTUME", title: "Carnival Top Hat", icon: "🎩", description: "Bolt is now the ringmaster." },
    { id: "sprocket.gear-tag", kind: "SPROCKET_ACCESSORY", title: "Gear Tag", icon: "⚙️", description: "A shiny gear for Sprocket's collar." },
    { id: "prop.cuckoo-clock", kind: "PROP", title: "Cuckoo Clock", icon: "🕰️", description: "It says 'cuckoo' sometimes. Mostly at the wrong time." },
    { id: "prop.golden-gear", kind: "PROP", title: "Golden Gear", icon: "🏆", description: "From the factory, with thanks." },
    // Builder Bay (M13)
    { id: "part.builder.beam-wood", kind: "PART", title: "Wooden Beam", icon: "🪵", description: "Light and handy. Not the strongest." },
    { id: "part.builder.beam-metal", kind: "PART", title: "Metal Beam", icon: "🔩", description: "Strong — and heavy." },
    { id: "part.builder.brace", kind: "PART", title: "Triangle Brace", icon: "📐", description: "Turns wobbly squares into steady triangles." },
    { id: "part.builder.column", kind: "PART", title: "Support Column", icon: "🏛️", description: "Holds things up from below." },
    { id: "part.builder.rope", kind: "PART", title: "Rope", icon: "🪢", description: "Great at pulling. Useless at pushing." },
    { id: "tool.stress-scanner", kind: "TOOL", title: "Stress Scanner", icon: "🩻", description: "Shows which parts are pulled, squashed and close to breaking — now in Free Build too." },
    { id: "sticker.bridge-builder", kind: "STICKER", title: "Bridge Builder", icon: "🌉", description: "Bolt crossed the canyon." },
    { id: "sticker.steady", kind: "STICKER", title: "Steady!", icon: "🧘", description: "You stopped the wobble." },
    { id: "sticker.triangle", kind: "STICKER", title: "Triangle Power", icon: "🔺", description: "Three sides, no wobble." },
    { id: "sticker.heavy-hauler", kind: "STICKER", title: "Heavy Hauler", icon: "🚚", description: "The heavy cart made it across." },
    { id: "sticker.crane-operator", kind: "STICKER", title: "Crane Operator", icon: "🏗️", description: "You built a working crane." },
    { id: "sticker.roof-rescuer", kind: "STICKER", title: "Roof Rescuer", icon: "🏠", description: "The roof held and Bolt walked through." },
    { id: "sticker.sky-high", kind: "STICKER", title: "Sky High", icon: "🗼", description: "A tower above the flag." },
    { id: "sticker.egg-saver", kind: "STICKER", title: "Egg Saver", icon: "🥚", description: "Not a crack!" },
    { id: "sticker.bridge-scientist", kind: "STICKER", title: "Bridge Scientist", icon: "🔬", description: "You compared two bridges fairly." },
    { id: "badge.parade-bridge", kind: "BADGE", title: "Parade Bridge Builder", icon: "🎉", description: "The Robot Parade crossed your bridge!" },
    { id: "badge.builder-bay", kind: "BADGE", title: "Builder Bay Restored", icon: "🏅", description: "Builder Bay is sturdy again!" },
    { id: "bolt.builder-hat", kind: "BOLT_COSTUME", title: "Builder's Helmet", icon: "👷", description: "Bolt is now officially in charge of safety." },
    { id: "prop.toy-elephant", kind: "PROP", title: "Toy Elephant", icon: "🐘", description: "A tiny copy of the parade elephant." },
    // Power Lab (M14)
    { id: "part.circuit.battery", kind: "PART", title: "Battery", icon: "🔋", description: "Pushes electricity round a loop." },
    { id: "part.circuit.wire", kind: "PART", title: "Wire", icon: "〰️", description: "Joins things. Only its two ends connect." },
    { id: "part.circuit.bulb", kind: "PART", title: "Bulb", icon: "💡", description: "Glows when electricity flows through it." },
    { id: "part.circuit.switch", kind: "PART", title: "Switch", icon: "🎚️", description: "Opens and closes a gap in the loop. Tap it to flip it." },
    { id: "part.circuit.button", kind: "PART", title: "Button", icon: "🔴", description: "Closes the loop only while it's pressed." },
    { id: "part.circuit.motor", kind: "PART", title: "Electric Motor", icon: "⚙️", description: "Turns when electricity flows. Swap + and − to turn the other way." },
    { id: "part.circuit.splitter", kind: "PART", title: "Splitter", icon: "🟡", description: "A post where lots of wires can meet." },
    { id: "part.circuit.buzzer", kind: "PART", title: "Buzzer", icon: "🔔", description: "BZZZZ. (Sorry.)" },
    { id: "part.circuit.battery-big", kind: "PART", title: "Big Battery", icon: "🔋", description: "Same push, lasts much longer." },
    { id: "tool.circuit-scanner", kind: "TOOL", title: "Circuit Scanner", icon: "⚡", description: "Shows the current in every wire and which machines have no power — now in Free Build too." },
    { id: "sticker.first-light", kind: "STICKER", title: "First Light", icon: "💡", description: "You lit your first bulb." },
    { id: "sticker.loop-fixer", kind: "STICKER", title: "Loop Fixer", icon: "🔧", description: "You found the break in the loop." },
    { id: "sticker.button-pusher", kind: "STICKER", title: "Button Pusher", icon: "🔴", description: "Push it, light it." },
    { id: "sticker.motor-power", kind: "STICKER", title: "Motor Power", icon: "⚡", description: "Electricity moved the old conveyor." },
    { id: "sticker.two-lights", kind: "STICKER", title: "Double Glow", icon: "✨", description: "Two lights, one battery." },
    { id: "sticker.path-finder", kind: "STICKER", title: "Path Finder", icon: "🛤️", description: "A path for each bulb." },
    { id: "sticker.lift-power", kind: "STICKER", title: "Power Lift", icon: "🏗️", description: "Motor, gears and a switch lifted the crate." },
    { id: "sticker.battery-saver", kind: "STICKER", title: "Battery Saver", icon: "🔋", description: "Job done, battery saved." },
    { id: "sticker.battery-scientist", kind: "STICKER", title: "Battery Scientist", icon: "🔬", description: "One battery or two — you tested it fairly." },
    { id: "prop.duck-alarm", kind: "PROP", title: "Duck Alarm", icon: "🚨", description: "Guards the workshop. Quack." },
    { id: "sprocket.glow-collar", kind: "SPROCKET_ACCESSORY", title: "Glow Collar", icon: "💡", description: "Sprocket lights up the dark." },
    { id: "avatar.spark-visor", kind: "AVATAR", title: "Spark Visor", icon: "🕶️", description: "For looking cool near lightning." },
    { id: "badge.power-grid", kind: "BADGE", title: "Grid Restorer", icon: "🔌", description: "You reconnected the campus power grid." },
    // Magnet Factory (M15)
    { id: "part.magnetic.bar", kind: "PART", title: "Bar Magnet", icon: "🧲", description: "N at one end, S at the other. Tap to turn it." },
    { id: "part.magnetic.puck", kind: "PART", title: "Magnet Puck", icon: "🧲", description: "A small magnet that can ride on things." },
    { id: "part.magnetic.floater", kind: "PART", title: "Ring Magnet", icon: "⭕", description: "A ring magnet for guide rods." },
    { id: "part.magnetic.electromagnet", kind: "PART", title: "Electromagnet", icon: "⚡", description: "A magnet you switch on with electricity." },
    { id: "part.scrap.iron-block", kind: "PART", title: "Iron Block", icon: "⬛", description: "Magnets love it." },
    { id: "tool.magnet-scanner", kind: "TOOL", title: "Magnet Scanner", icon: "🧲", description: "Shows magnetic fields and every magnetic push and pull — now in Free Build too." },
    { id: "sticker.magnet-pull", kind: "STICKER", title: "Opposites Attract", icon: "🧲", description: "N met S." },
    { id: "sticker.magnet-push", kind: "STICKER", title: "Hands Off!", icon: "🙌", description: "Pushed without touching." },
    { id: "sticker.metal-sorter", kind: "STICKER", title: "Metal Detector", icon: "🔩", description: "Only the magnetic ones." },
    { id: "sticker.no-touch", kind: "STICKER", title: "Magnet Parking", icon: "🅿️", description: "Parked between two pushes." },
    { id: "sticker.scrap-sorter", kind: "STICKER", title: "Scrap Sorter", icon: "♻️", description: "The old conveyor sorts scrap again." },
    { id: "sticker.magnet-train", kind: "STICKER", title: "Magnet Express", icon: "🚂", description: "Cargo moved by a riding magnet." },
    { id: "sticker.floating", kind: "STICKER", title: "Float!", icon: "🪄", description: "A magnet floated on its rod." },
    { id: "sticker.crane-magnet", kind: "STICKER", title: "Crane Operator", icon: "🏗️", description: "Grab, carry, drop." },
    { id: "sticker.material-scientist", kind: "STICKER", title: "Material Scientist", icon: "🔬", description: "You tested every sample fairly." },
    { id: "prop.magnet-sandwich", kind: "PROP", title: "Floating Sandwich", icon: "🥪", description: "Still floating. Still not edible." },
    { id: "sprocket.magnet-tag", kind: "SPROCKET_ACCESSORY", title: "Magnet Tag", icon: "🧲", description: "Sprocket's collar sticks to the fridge now." },
    { id: "avatar.magnet-headband", kind: "AVATAR", title: "Magnet Headband", icon: "🧲", description: "Attracts attention." },
    { id: "badge.scrap-sorter", kind: "BADGE", title: "Giant Sorter Restorer", icon: "♻️", description: "The Giant Scrap Sorter runs again." },
    { id: "badge.magnet-factory", kind: "BADGE", title: "Magnet Factory Restored", icon: "🏅", description: "The Magnet Factory is humming again!" },
    // Water Works (M16)
    { id: "part.plumb.pipe", kind: "PART", title: "Pipe", icon: "🟦", description: "Water follows it. Only its two ends join on." },
    { id: "part.plumb.tank", kind: "PART", title: "Tank", icon: "🛢️", description: "Holds water — until it's full." },
    { id: "part.plumb.valve", kind: "PART", title: "Valve", icon: "🚰", description: "Tap it to open or shut." },
    { id: "part.plumb.nozzle", kind: "PART", title: "Nozzle", icon: "💦", description: "Turns water pressure into a jet. Tap to aim." },
    { id: "part.plumb.pump", kind: "PART", title: "Water Pump", icon: "⚡", description: "Pushes water uphill — with electricity." },
    { id: "part.plumb.pipe-narrow", kind: "PART", title: "Narrow Pipe", icon: "➖", description: "Lets less water through." },
    { id: "part.plumb.wheel", kind: "PART", title: "Water Wheel", icon: "☸️", description: "Falling water turns it. Gears go on its shaft." },
    { id: "part.plumb.sprinkler", kind: "PART", title: "Sprinkler", icon: "🌱", description: "Showers the ground below." },
    { id: "tool.flow-scanner", kind: "TOOL", title: "Flow Scanner", icon: "💧", description: "Shows how much water flows in every pipe — now in Free Build too." },
    { id: "sticker.tank-filler", kind: "STICKER", title: "Tank Filler", icon: "🛢️", description: "Your first full tank." },
    { id: "sticker.downhill", kind: "STICKER", title: "Downhill All the Way", icon: "⛰️", description: "Gravity did the work." },
    { id: "sticker.valve-master", kind: "STICKER", title: "Valve Master", icon: "🚰", description: "Open here, shut there." },
    { id: "sticker.leak-fixer", kind: "STICKER", title: "Leak Fixer", icon: "🔧", description: "Bolt's box stayed dry." },
    { id: "sticker.gardener", kind: "STICKER", title: "Gardener", icon: "🌻", description: "Three happy beds." },
    { id: "sticker.water-wheel", kind: "STICKER", title: "Mill Wheel", icon: "☸️", description: "Water turned the fan." },
    { id: "sticker.pump-up", kind: "STICKER", title: "Pump It Up", icon: "⬆️", description: "Water went uphill." },
    { id: "sticker.sharpshooter", kind: "STICKER", title: "Sharpshooter", icon: "🎯", description: "Two targets, two jets." },
    { id: "sticker.pipe-scientist", kind: "STICKER", title: "Pipe Scientist", icon: "🔬", description: "Wide pipe or narrow — you tested it fairly." },
    { id: "prop.duck-flume", kind: "PROP", title: "Duck Flume", icon: "🦆", description: "Wheee! Splash!" },
    { id: "sprocket.rain-hat", kind: "SPROCKET_ACCESSORY", title: "Rain Hat", icon: "🌂", description: "Sprocket stays dry. Mostly." },
    { id: "avatar.snorkel", kind: "AVATAR", title: "Snorkel Mask", icon: "🤿", description: "For very wet experiments." },
    { id: "badge.grand-fountain", kind: "BADGE", title: "Fountain Restorer", icon: "⛲", description: "The Grand Fountain sprays again!" },
    { id: "badge.water-works", kind: "BADGE", title: "Water Works Restored", icon: "🏅", description: "The water is flowing again!" },
    // Flight Hangar (M17)
    { id: "part.flight.fan", kind: "PART", title: "Wind Fan", icon: "🌬️", description: "Blows a breeze. Tap it to turn it." },
    { id: "part.flight.glider", kind: "PART", title: "Glider Body", icon: "✈️", description: "Clip wings, a tail and more onto it." },
    { id: "part.flight.wing-large", kind: "PART", title: "Big Wing", icon: "🪽", description: "Lots of lift." },
    { id: "part.flight.wing-small", kind: "PART", title: "Small Wing", icon: "🪽", description: "Light and quick." },
    { id: "part.flight.tail", kind: "PART", title: "Tail", icon: "🛩️", description: "Keeps the nose steady." },
    { id: "part.flight.parachute", kind: "PART", title: "Parachute", icon: "🪂", description: "For soft landings." },
    { id: "part.flight.balloon", kind: "PART", title: "Balloon", icon: "🎈", description: "A little upward push." },
    { id: "part.flight.propeller", kind: "PART", title: "Propeller", icon: "🌀", description: "Pushes forwards — needs a battery pack." },
    { id: "part.flight.power-pack", kind: "PART", title: "Battery Pack", icon: "🔋", description: "Powers a propeller for a little while." },
    { id: "tool.air-scanner", kind: "TOOL", title: "Air Scanner", icon: "🌬️", description: "Shows lift, weight, thrust and drag on flying machines — now in Free Build too." },
    { id: "sticker.breezy", kind: "STICKER", title: "Breezy", icon: "🌬️", description: "Blown into place." },
    { id: "sticker.long-glide", kind: "STICKER", title: "Long Glide", icon: "🛫", description: "Past the flag!" },
    { id: "sticker.soft-landing", kind: "STICKER", title: "Soft Landing", icon: "🪂", description: "Gently does it." },
    { id: "sticker.balloon-lift", kind: "STICKER", title: "Up, Up and Away", icon: "🎈", description: "Lifted by balloons." },
    { id: "sticker.hoops", kind: "STICKER", title: "Hoop Flyer", icon: "⭕", description: "Through both hoops." },
    { id: "sticker.balanced", kind: "STICKER", title: "Steady Flyer", icon: "⚖️", description: "No more flips." },
    { id: "sticker.propeller", kind: "STICKER", title: "Propeller Power", icon: "🌀", description: "Took off under its own power." },
    { id: "sticker.canyon", kind: "STICKER", title: "Canyon Hopper", icon: "🏜️", description: "Across the gap." },
    { id: "sticker.wing-scientist", kind: "STICKER", title: "Wing Scientist", icon: "🔬", description: "A fair flight test." },
    { id: "prop.toy-plane", kind: "PROP", title: "Toy Plane", icon: "🛩️", description: "Loops around the workshop." },
    { id: "sprocket.flying-goggles", kind: "SPROCKET_ACCESSORY", title: "Flying Goggles", icon: "🥽", description: "Sprocket, ace pilot." },
    { id: "avatar.aviator-cap", kind: "AVATAR", title: "Aviator Cap", icon: "🧑‍✈️", description: "Chocks away!" },
    { id: "badge.canyon-flyer", kind: "BADGE", title: "Canyon Flyer", icon: "🛩️", description: "Crossed the workshop canyon and landed softly." },
    { id: "badge.flight-hangar", kind: "BADGE", title: "Flight Hangar Restored", icon: "🏅", description: "Planes are flying again!" },
    // Robot Lab (M18)
    { id: "part.robot.bot", kind: "PART", title: "Robot", icon: "🤖", description: "Program it with blocks." },
    { id: "tool.program-debugger", kind: "TOOL", title: "Program Debugger", icon: "🐞", description: "Shows which block each robot is running — now in Free Build too." },
    { id: "sticker.first-program", kind: "STICKER", title: "First Program", icon: "🤖", description: "One block, one flag." },
    { id: "sticker.corner", kind: "STICKER", title: "Round the Bend", icon: "↩️", description: "Turned the corner." },
    { id: "sticker.patience", kind: "STICKER", title: "Patience", icon: "⏱️", description: "Waited for the right moment." },
    { id: "sticker.wall-sense", kind: "STICKER", title: "Wall Sense", icon: "🧱", description: "A rule that never bumps." },
    { id: "sticker.colour-coder", kind: "STICKER", title: "Colour Coder", icon: "🌈", description: "Followed the colours." },
    { id: "sticker.button-bot", kind: "STICKER", title: "Button Bot", icon: "🔴", description: "Pressed the button." },
    { id: "sticker.delivery-bot", kind: "STICKER", title: "Delivery Bot", icon: "📦", description: "Delivered the box." },
    { id: "sticker.factory-bot", kind: "STICKER", title: "Factory Bot", icon: "🏭", description: "Ran the packing cell." },
    { id: "sticker.route-scientist", kind: "STICKER", title: "Route Scientist", icon: "🔬", description: "Raced two routes fairly." },
    { id: "prop.disco-ball", kind: "PROP", title: "Disco Ball", icon: "🪩", description: "For robot dance parties." },
    { id: "sprocket.antenna", kind: "SPROCKET_ACCESSORY", title: "Robot Antenna", icon: "📡", description: "Sprocket receives signals now. Mostly about snacks." },
    { id: "avatar.coder-visor", kind: "AVATAR", title: "Coder Visor", icon: "🥽", description: "See the code in everything." },
    { id: "badge.automated-factory", kind: "BADGE", title: "Factory Automator", icon: "🏭", description: "The Automated Factory runs itself." },
    { id: "badge.robot-lab", kind: "BADGE", title: "Robot Lab Restored", icon: "🏅", description: "The robots are back to work!" },
    // Space Centre (M19)
    { id: "part.space.rover", kind: "PART", title: "Rover", icon: "🛻", description: "Wheels, a motor and power — off it goes." },
    { id: "part.space.rocket", kind: "PART", title: "Rocket", icon: "🚀", description: "Boosters, fins and a nose cone." },
    { id: "tool.gravity-meter", kind: "TOOL", title: "Gravity Meter", icon: "⚖️", description: "Shows mass and weight in any gravity — now in Free Build too." },
    { id: "sticker.moon-rover", kind: "STICKER", title: "Moon Rover", icon: "🛻", description: "Built a rover." },
    { id: "sticker.crater", kind: "STICKER", title: "Crater Climber", icon: "⛰️", description: "Climbed out of the crater." },
    { id: "sticker.straight-up", kind: "STICKER", title: "Straight Up", icon: "🚀", description: "Through all three rings." },
    { id: "sticker.bullseye", kind: "STICKER", title: "Bullseye", icon: "🎯", description: "Hit the target." },
    { id: "sticker.soft-landing", kind: "STICKER", title: "Soft Landing", icon: "🛬", description: "Touched down gently." },
    { id: "sticker.sunny", kind: "STICKER", title: "Sunny Side", icon: "☀️", description: "Faced the sun." },
    { id: "sticker.space-mechanic", kind: "STICKER", title: "Space Mechanic", icon: "🦾", description: "Fixed the satellite with a robot arm." },
    { id: "sticker.moon-delivery", kind: "STICKER", title: "Moon Delivery", icon: "📦", description: "Delivered to the base." },
    { id: "sticker.fair-test", kind: "STICKER", title: "Fair Test", icon: "⚖️", description: "Same thing, two gravities." },
    { id: "prop.mini-rocket", kind: "PROP", title: "Mini Rocket", icon: "🚀", description: "A rocket for the shelf." },
    { id: "sprocket.space-helmet", kind: "SPROCKET_ACCESSORY", title: "Space Helmet", icon: "👩‍🚀", description: "Sprocket is ready for the Moon. The tail doesn't fit, but never mind." },
    { id: "avatar.astronaut", kind: "AVATAR", title: "Astronaut", icon: "🧑‍🚀", description: "One small step…" },
    { id: "badge.wobbleworks-explorer", kind: "BADGE", title: "WobbleWorks Explorer", icon: "🌙", description: "Launch, land and drive — all in one go." },
    { id: "badge.space-centre", kind: "BADGE", title: "Space Centre Restored", icon: "🏅", description: "The launch tower stands again!" },
    // Chain Reaction Workshop (M21)
    // Creature & Music Machines (M29) parts, unlocked for Free Build by the challenges.
    { id: "part.creature.body", kind: "PART", title: "Creature Body", icon: "🐾", description: "The body that creature parts clip onto." },
    { id: "part.creature.spring-leg", kind: "PART", title: "Spring Leg", icon: "🌀", description: "Wind it up — boing!" },
    { id: "part.creature.leg", kind: "PART", title: "Leg", icon: "🦵", description: "Walks, with a motor and a battery." },
    { id: "part.creature.wing", kind: "PART", title: "Flapping Wing", icon: "🪽", description: "Flaps with power." },
    { id: "part.creature.motor", kind: "PART", title: "Creature Motor", icon: "⚙️", description: "Makes legs and wings move (needs a battery)." },
    { id: "part.creature.claw", kind: "PART", title: "Claw", icon: "🦀", description: "Pinches what it can reach." },
    { id: "part.creature.segment", kind: "PART", title: "Body Segment", icon: "🐛", description: "Join a few for a wiggly crawler." },
    { id: "part.creature.big-leg", kind: "PART", title: "Big Leg", icon: "🦖", description: "Carries heavy loads." },
    { id: "part.music.tone-block", kind: "PART", title: "Tone Block", icon: "🪵", description: "Tock!" },
    { id: "part.music.drum", kind: "PART", title: "Drum", icon: "🥁", description: "Boom!" },
    { id: "part.music.beater", kind: "PART", title: "Beater", icon: "🔨", description: "Strikes once every turn." },
    { id: "part.music.chime", kind: "PART", title: "Chime", icon: "🎐", description: "Ting — even under a water jet." },
    { id: "part.music.horn", kind: "PART", title: "Electric Horn", icon: "📯", description: "Toots while it has power." },
    { id: "part.music.timer", kind: "PART", title: "Timer Switch", icon: "⏱️", description: "Clicks on at a steady beat." },
    { id: "part.chain.domino", kind: "PART", title: "Dominoes", icon: "🁢", description: "Line them up and knock them down." },
    { id: "part.chain.bell", kind: "PART", title: "Bell", icon: "🔔", description: "Ding!" },
    { id: "part.chain.seesaw", kind: "PART", title: "Seesaw", icon: "⚖️", description: "Down one end, up the other." },
    { id: "part.chain.trapdoor", kind: "PART", title: "Trapdoor", icon: "🚪", description: "Holds something until it's set off." },
    { id: "part.chain.cannon", kind: "PART", title: "Duck Cannon", icon: "🦆", description: "Fires the duck when it's set off." },
    { id: "part.chain.confetti", kind: "PART", title: "Confetti Ring", icon: "🎊", description: "Bursts when something flies through." },
    { id: "part.chain.counter", kind: "PART", title: "Chain Counter", icon: "⛓️", description: "Counts real cause-and-effect steps — in Free Build too." },
    { id: "sticker.first-domino", kind: "STICKER", title: "First Domino", icon: "🁢", description: "Five steps to the bell." },
    { id: "sticker.bell-ringer", kind: "STICKER", title: "Bell Ringer", icon: "🔔", description: "Five bells, one push." },
    { id: "sticker.up-down", kind: "STICKER", title: "Up, Down, Around", icon: "🔄", description: "Roll, lift and spin." },
    { id: "sticker.power-change", kind: "STICKER", title: "Power Change", icon: "⚡", description: "Rolling to electric to turning." },
    { id: "sticker.wet-wild", kind: "STICKER", title: "Wet and Wild", icon: "💦", description: "Water in the middle." },
    { id: "sticker.magnet-middle", kind: "STICKER", title: "Magnetic Middle", icon: "🧲", description: "A pull without touching." },
    { id: "sticker.robot-relay", kind: "STICKER", title: "Robot Relay", icon: "🦾", description: "The robot passed it on." },
    { id: "sticker.air-mail", kind: "STICKER", title: "Air Mail", icon: "✉️", description: "Delivered by breeze." },
    { id: "sticker.three-domains", kind: "STICKER", title: "Three Domains", icon: "🧩", description: "Three kinds of machine." },
    { id: "sticker.no-repeats", kind: "STICKER", title: "No Repeats", icon: "🎨", description: "Ten different parts." },
    { id: "sticker.long-haul", kind: "STICKER", title: "Long Haul", icon: "⏳", description: "Twenty seconds of chain." },
    { id: "prop.domino-tower", kind: "PROP", title: "Domino Tower", icon: "🁢", description: "Don't breathe on it." },
    { id: "sprocket.party-hat", kind: "SPROCKET_ACCESSORY", title: "Party Hat", icon: "🎉", description: "Sprocket loves a grand finale." },
    { id: "badge.chain-master", kind: "BADGE", title: "Chain Reaction Master", icon: "⛓️", description: "The Duck Finale — fifteen steps and a flying duck!" },
    // Experiment Lab (M22)
    { id: "tool.lab-notebook", kind: "TOOL", title: "Lab Notebook", icon: "📓", description: "Keeps your saved experiments." },
    ...[["ramp", "📐", "Ramp Scientist"], ["grip", "🧤", "Grip Scientist"], ["gear", "⚙️", "Gear Scientist"], ["bridge", "🌉", "Bridge Scientist"], ["battery", "🔋", "Battery Scientist"], ["magnet", "🧲", "Magnet Scientist"], ["pipe", "💧", "Pipe Scientist"], ["wing", "🪽", "Wing Scientist"], ["route", "🤖", "Route Scientist"], ["bounce", "🏀", "Bounce Scientist"], ["gravity", "🌙", "Gravity Scientist"]].map(([k, icon, title]) => ({ id: `sticker.exp-${k}`, kind: "STICKER", title, icon, description: "Saved a fair-test experiment." })),
    { id: "avatar.lab-coat", kind: "AVATAR", title: "Lab Coat", icon: "🥼", description: "Every good scientist needs one." },
    { id: "prop.lab-flask", kind: "PROP", title: "Bubbling Flask", icon: "⚗️", description: "Bubbles. Doesn't do anything else." },
    { id: "badge.fair-tester", kind: "BADGE", title: "Fair Tester", icon: "🔬", description: "Saved an experiment that changed just one thing." },
    { id: "badge.power-lab", kind: "BADGE", title: "Power Lab Restored", icon: "🏅", description: "The lights are on in the Power Lab!" },
    // hidden prototype lab key pieces — one from a silly mission in each of the first three labs (exploration, never stars)
    { id: "key.prototype-1", kind: "KEY_PIECE", title: "Strange Key Piece", icon: "🗝️", description: "A piece of something. It hums." },
    { id: "key.prototype-2", kind: "KEY_PIECE", title: "Another Strange Key Piece", icon: "🗝️", description: "It fits the first one. Sort of." },
    { id: "key.prototype-3", kind: "KEY_PIECE", title: "Last Strange Key Piece", icon: "🗝️", description: "Somewhere, a door is waiting." },
    // Grand Invention Hall (M32): a sticker per challenge, and the finale's badge (it marks the campaign complete).
    { id: "sticker.grand-ultimate-delivery", kind: "STICKER", title: "Ultimate Deliverer", icon: "📦", description: "Grand Invention Hall: Three deliveries, three ways." },
    { id: "sticker.grand-three-system-rescue", kind: "STICKER", title: "Triple Rescuer", icon: "🛟", description: "Grand Invention Hall: Gears, a bridge and a ramp to the rescue." },
    { id: "sticker.grand-egg-extreme", kind: "STICKER", title: "Egg Guardian", icon: "🥚", description: "Grand Invention Hall: Two drops, not one crack." },
    { id: "sticker.grand-power-saving-factory", kind: "STICKER", title: "Power Saver", icon: "🔋", description: "Grand Invention Hall: Ran the factory without wasting power." },
    { id: "sticker.grand-magnetic-water-lift", kind: "STICKER", title: "Magnet & Water Lifter", icon: "🧲", description: "Grand Invention Hall: Lifted with magnets, then with water." },
    { id: "sticker.grand-autonomous-bridge", kind: "STICKER", title: "Robot Bridge Builder", icon: "🤖", description: "Grand Invention Hall: A robot fetched, a bridge held." },
    { id: "sticker.grand-flight-robot-relay", kind: "STICKER", title: "Relay Runner", icon: "✈️", description: "Grand Invention Hall: Flew it across, then the robot took over." },
    { id: "sticker.grand-great-bell-machine", kind: "STICKER", title: "Bell Master", icon: "🔔", description: "Grand Invention Hall: Rang every bell on campus." },
    { id: "sticker.grand-bolt-rescue", kind: "STICKER", title: "Bolt's Hero", icon: "🦺", description: "Grand Invention Hall: Got Bolt safely off the roof!" },
    { id: "sticker.grand-sprockets-shortcut", kind: "STICKER", title: "Shortcut Champion", icon: "🐕", description: "Grand Invention Hall: Beat Sprocket's clock." },
    { id: "sticker.grand-giant-chain-reaction", kind: "STICKER", title: "Giant Chain Maker", icon: "⛓️", description: "Grand Invention Hall: The biggest chain reactions on campus." },
    // Hidden Prototype Lab (M33): stickers, rare cosmetics and the secret badge.
    { id: "sticker.proto-reverse-conveyor", kind: "STICKER", title: "Backwards Thinker", icon: "🔄", description: "Prototype Lab: Made a backwards conveyor go forwards." },
    { id: "sticker.proto-super-spring", kind: "STICKER", title: "Spring Tamer", icon: "🌀", description: "Prototype Lab: Tamed the Super Spring." },
    { id: "sticker.proto-magnet-maze", kind: "STICKER", title: "Maze Magnetist", icon: "🧲", description: "Prototype Lab: Steered a puck with magnets alone." },
    { id: "sticker.proto-worm-gear-box", kind: "STICKER", title: "Worm Gear Wizard", icon: "🐛", description: "Prototype Lab: Lifted the heaviest crate ever." },
    { id: "sticker.proto-tiny-factory", kind: "STICKER", title: "Tiny Factory Boss", icon: "🏭", description: "Prototype Lab: A whole machine in a tiny space." },
    { id: "sticker.proto-no-wheels-allowed", kind: "STICKER", title: "No-Wheels Hero", icon: "🚫", description: "Prototype Lab: Moved Bolt without a single wheel." },
    { id: "sticker.proto-five-systems", kind: "STICKER", title: "Five-System Chain", icon: "5️⃣", description: "Prototype Lab: Five systems in one chain reaction." },
    { id: "sticker.proto-sprocket-shortcut", kind: "STICKER", title: "Shortcut Finder", icon: "⏱️", description: "Prototype Lab: Beat Sprocket's old route." },
    { id: "sprocket.bubble-helmet", kind: "SPROCKET_ACCESSORY", title: "Bubble Helmet", icon: "🫧", description: "A rare prototype: Sprocket's very own bubble." },
    { id: "bolt.prototype-goggles", kind: "BOLT_COSTUME", title: "Prototype Goggles", icon: "🥽", description: "Rare! Upside-down-proof goggles from the secret lab." },
    { id: "frame.blueprint", kind: "FRAME", title: "Blueprint Frame", icon: "📐", description: "A rare frame for your wobbliest inventions." },
    { id: "bolt.memory-spark", kind: "BOLT_COSTUME", title: "Memory Spark", icon: "✨", description: "The rarest of all: Bolt remembers everything now." },
    { id: "badge.prototype-lab", kind: "BADGE", title: "Prototype Pioneer", icon: "❓", description: "Finished every challenge in the Hidden Prototype Lab." },
    { id: "badge.campus-restored", kind: "BADGE", title: "WobbleWorks Restored", icon: "🏛️", description: "The Great WobbleWorks Machine runs — the whole campus is alive again!" }
];
export function rewardById(id) { return REWARDS.find(r => r.id === id); }
export const MISSION_REWARDS = Object.freeze({
    "motion.roll-with-it": { onComplete: ["sticker.first-roll"], onAllStars: ["avatar.cap"] },
    "motion.ramp-rescue": { onComplete: ["sticker.safe-landing", "part.motion.axle"] },
    "motion.too-fast": { onComplete: ["sticker.brake-master", "part.motion.friction-high"], onAllStars: ["avatar.hard-hat"] },
    "motion.spring-delivery": { onComplete: ["sticker.special-delivery", "frame.wood"] },
    "motion.slippery-business": { onComplete: ["sticker.slip-n-grip", "part.motion.friction-low"] },
    "motion.bounce-around": { onComplete: ["sticker.boing", "part.motion.bounce-pad"], onAllStars: ["sprocket.spring-collar"] },
    "motion.heavy-or-light": { onComplete: ["sticker.heavy-light", "tool.force-scanner"] },
    "motion.make-it-farther": { onComplete: ["sticker.far-out", "part.motion.roller"] },
    "motion.which-ramp-wins": { onComplete: ["sticker.scientist", "avatar.goggles"] },
    "motion.duck-cannon": { onComplete: ["prop.bath-tub", "bolt.duck-floatie", "key.prototype-1"], onAllStars: ["prop.rubber-duck"] },
    "motion.giant-marble-delivery": { onComplete: ["badge.mega-marble", "bolt.racing-stripes"], onAllStars: ["frame.gold"] },
    "motion.runaway-test-cart": { onComplete: ["badge.motion-yard", "sprocket.bandana", "prop.test-flag"] },
    // Later labs (content arrives at M12/M13): their silly missions hold the other two key pieces.
    "gear.turn-the-door": { onComplete: ["sticker.door-opener", "part.gear.crank", "part.gear.medium"] },
    "gear.wrong-way-round": { onComplete: ["sticker.wrong-way", "part.gear.small"] },
    "gear.speed-it-up": { onComplete: ["sticker.speedy-spin", "part.gear.large"] },
    "gear.slow-and-strong": { onComplete: ["sticker.strongman", "tool.spin-scanner"] },
    "gear.lift-bolt": { onComplete: ["sticker.going-up", "part.gear.belt-pulley", "part.gear.belt-pulley-big"] },
    "gear.three-fans": { onComplete: ["sticker.triple-breeze"] },
    "gear.clockwork-trouble": { onComplete: ["sticker.clock-fixer", "prop.cuckoo-clock"] },
    "gear.conveyor-rescue": { onComplete: ["sticker.conveyor", "part.gear.motor"] },
    "gear.big-gear-vs-small-gear": { onComplete: ["sticker.gear-scientist"] },
    "gear.spin-sprocket": { onComplete: ["key.prototype-2"], onAllStars: ["sprocket.gear-tag"] },
    "gear.the-clockwork-carnival": { onComplete: ["badge.clockwork-carnival", "bolt.top-hat"] },
    "gear.jammed-factory-drive": { onComplete: ["badge.gear-garage", "prop.golden-gear"] },
    "builder.bridge-the-gap": { onComplete: ["sticker.bridge-builder", "part.builder.beam-wood"] },
    "builder.stop-the-wobble": { onComplete: ["sticker.steady", "part.builder.brace"] },
    "builder.triangle-power": { onComplete: ["sticker.triangle", "part.builder.column"] },
    "builder.heavy-delivery": { onComplete: ["sticker.heavy-hauler", "part.builder.beam-metal"] },
    "builder.build-a-crane": { onComplete: ["sticker.crane-operator", "part.builder.rope"] },
    "builder.roof-rescue": { onComplete: ["sticker.roof-rescuer", "tool.stress-scanner"] },
    "builder.tallest-tower": { onComplete: ["sticker.sky-high"] },
    "builder.keep-the-egg-safe": { onComplete: ["sticker.egg-saver"] },
    "builder.which-bridge-holds-more": { onComplete: ["sticker.bridge-scientist"] },
    "builder.elephant-robot-parade": { onComplete: ["key.prototype-3"], onAllStars: ["prop.toy-elephant"] },
    "builder.the-robot-parade-bridge": { onComplete: ["badge.parade-bridge", "bolt.builder-hat"] },
    "builder.collapsing-workshop-roof": { onComplete: ["badge.builder-bay"] },
    "power.light-it-up": { onComplete: ["sticker.first-light", "part.circuit.battery", "part.circuit.wire", "part.circuit.bulb"] },
    "power.broken-loop": { onComplete: ["sticker.loop-fixer", "part.circuit.switch"] },
    "power.push-the-button": { onComplete: ["sticker.button-pusher", "part.circuit.button"] },
    "power.motor-power": { onComplete: ["sticker.motor-power", "part.circuit.motor"] },
    "power.two-lights": { onComplete: ["sticker.two-lights", "part.circuit.splitter"] },
    "power.which-path": { onComplete: ["sticker.path-finder", "tool.circuit-scanner"] },
    "power.power-the-lift": { onComplete: ["sticker.lift-power"] },
    "power.save-the-battery": { onComplete: ["sticker.battery-saver", "part.circuit.battery-big"] },
    "power.one-battery-or-two": { onComplete: ["sticker.battery-scientist"] },
    "power.buzz-the-duck": { onComplete: ["part.circuit.buzzer", "prop.duck-alarm"], onAllStars: ["sprocket.glow-collar"] },
    "power.restore-the-power-grid": { onComplete: ["badge.power-grid", "avatar.spark-visor"] },
    "power.blackout": { onComplete: ["badge.power-lab"] },
    "magnet.pull-it-in": { onComplete: ["sticker.magnet-pull", "part.magnetic.bar"] },
    "magnet.push-it-away": { onComplete: ["sticker.magnet-push"] },
    "magnet.metal-only": { onComplete: ["sticker.metal-sorter", "tool.magnet-scanner", "part.scrap.iron-block"] },
    "magnet.no-touching": { onComplete: ["sticker.no-touch"] },
    "magnet.scrap-sorter": { onComplete: ["sticker.scrap-sorter"] },
    "magnet.magnet-transport": { onComplete: ["sticker.magnet-train", "part.magnetic.puck"] },
    "magnet.floating-trick": { onComplete: ["sticker.floating", "part.magnetic.floater"] },
    "magnet.electromagnet-crane": { onComplete: ["sticker.crane-magnet", "part.magnetic.electromagnet"] },
    "magnet.which-materials-move": { onComplete: ["sticker.material-scientist"] },
    "magnet.magnetic-sandwich": { onComplete: ["prop.magnet-sandwich"], onAllStars: ["sprocket.magnet-tag"] },
    "magnet.the-giant-scrap-sorter": { onComplete: ["badge.scrap-sorter", "avatar.magnet-headband"] },
    "magnet.scrap-avalanche": { onComplete: ["badge.magnet-factory"] },
    "water.fill-the-tank": { onComplete: ["sticker.tank-filler", "part.plumb.pipe", "part.plumb.tank"] },
    "water.downhill-flow": { onComplete: ["sticker.downhill"] },
    "water.turn-the-valve": { onComplete: ["sticker.valve-master", "part.plumb.valve"] },
    "water.stop-the-leak": { onComplete: ["sticker.leak-fixer", "tool.flow-scanner"] },
    "water.water-the-garden": { onComplete: ["sticker.gardener", "part.plumb.sprinkler"] },
    "water.spin-the-wheel": { onComplete: ["sticker.water-wheel", "part.plumb.wheel"] },
    "water.pump-it-up": { onComplete: ["sticker.pump-up", "part.plumb.pump"] },
    "water.spray-the-target": { onComplete: ["sticker.sharpshooter", "part.plumb.nozzle"] },
    "water.which-pipe-fills-faster": { onComplete: ["sticker.pipe-scientist", "part.plumb.pipe-narrow"] },
    "water.duck-water-park": { onComplete: ["prop.duck-flume"], onAllStars: ["sprocket.rain-hat"] },
    "water.the-grand-fountain": { onComplete: ["badge.grand-fountain", "avatar.snorkel"] },
    "water.flooded-workshop": { onComplete: ["badge.water-works"] },
    "flight.blow-it-over": { onComplete: ["sticker.breezy", "part.flight.fan"] },
    "flight.long-glide": { onComplete: ["sticker.long-glide", "part.flight.glider", "part.flight.wing-large", "part.flight.tail"] },
    "flight.safe-landing": { onComplete: ["sticker.soft-landing", "part.flight.parachute"] },
    "flight.balloon-lift": { onComplete: ["sticker.balloon-lift", "part.flight.balloon"] },
    "flight.through-the-hoops": { onComplete: ["sticker.hoops", "tool.air-scanner"] },
    "flight.balance-the-wings": { onComplete: ["sticker.balanced", "part.flight.wing-small"] },
    "flight.propeller-push": { onComplete: ["sticker.propeller", "part.flight.propeller", "part.flight.power-pack"] },
    "flight.cross-the-canyon": { onComplete: ["sticker.canyon"] },
    "flight.which-wing-flies-farther": { onComplete: ["sticker.wing-scientist"] },
    "flight.flying-sprocket": { onComplete: ["prop.toy-plane"], onAllStars: ["sprocket.flying-goggles"] },
    "flight.the-canyon-flyer": { onComplete: ["badge.canyon-flyer", "avatar.aviator-cap"] },
    "flight.falling-cargo": { onComplete: ["badge.flight-hangar"] },
    "robot.move-forward": { onComplete: ["sticker.first-program", "part.robot.bot"] },
    "robot.turn-the-corner": { onComplete: ["sticker.corner"] },
    "robot.wait-for-it": { onComplete: ["sticker.patience", "tool.program-debugger"] },
    "robot.avoid-the-wall": { onComplete: ["sticker.wall-sense"] },
    "robot.follow-the-colour": { onComplete: ["sticker.colour-coder"] },
    "robot.press-the-button": { onComplete: ["sticker.button-bot"] },
    "robot.carry-the-box": { onComplete: ["sticker.delivery-bot"] },
    "robot.factory-robot": { onComplete: ["sticker.factory-bot"] },
    "robot.which-route-is-faster": { onComplete: ["sticker.route-scientist"] },
    "robot.robot-dance-party": { onComplete: ["prop.disco-ball"], onAllStars: ["sprocket.antenna"] },
    "robot.automated-factory": { onComplete: ["badge.automated-factory", "avatar.coder-visor"] },
    "robot.robot-traffic-jam": { onComplete: ["badge.robot-lab"] },
    "space.build-the-rover": { onComplete: ["sticker.moon-rover", "part.space.rover"] },
    "space.cross-the-crater": { onComplete: ["sticker.crater"] },
    "space.launch-straight": { onComplete: ["sticker.straight-up", "part.space.rocket", "tool.gravity-meter"] },
    "space.reach-the-target": { onComplete: ["sticker.bullseye"] },
    "space.safe-touchdown": { onComplete: ["sticker.soft-landing"] },
    "space.satellite-power": { onComplete: ["sticker.sunny"] },
    "space.robot-arm-repair": { onComplete: ["sticker.space-mechanic"] },
    "space.moon-base-delivery": { onComplete: ["sticker.moon-delivery"] },
    "space.earth-gravity-vs-moon-gravity": { onComplete: ["sticker.fair-test"] },
    "space.space-duck": { onComplete: ["prop.mini-rocket"], onAllStars: ["sprocket.space-helmet"] },
    "space.the-wobbleworks-explorer": { onComplete: ["badge.wobbleworks-explorer", "avatar.astronaut"] },
    "space.broken-launch-tower": { onComplete: ["badge.space-centre"] },
    "chain.first-domino": { onComplete: ["sticker.first-domino", "part.chain.domino", "part.chain.bell", "part.chain.counter"] },
    "chain.bell-ringer": { onComplete: ["sticker.bell-ringer"] },
    "chain.up-down-around": { onComplete: ["sticker.up-down", "part.chain.seesaw"] },
    "chain.power-change": { onComplete: ["sticker.power-change"] },
    "chain.wet-and-wild": { onComplete: ["sticker.wet-wild", "part.chain.cannon", "part.chain.confetti"] },
    "chain.magnetic-middle": { onComplete: ["sticker.magnet-middle"] },
    "chain.robot-relay": { onComplete: ["sticker.robot-relay"] },
    "chain.air-mail": { onComplete: ["sticker.air-mail"] },
    "chain.three-domains": { onComplete: ["sticker.three-domains", "prop.domino-tower"] },
    "chain.no-repeats": { onComplete: ["sticker.no-repeats", "part.chain.trapdoor"] },
    "chain.long-haul": { onComplete: ["sticker.long-haul"] },
    "chain.duck-finale": { onComplete: ["badge.chain-master"], onAllStars: ["sprocket.party-hat"] },
    // Science Fairs (M28): a ribbon for an accepted entry.
    "fair.motion-makers": { onComplete: ["sticker.fair-1"] },
    "fair.strong-and-powered": { onComplete: ["sticker.fair-2"] },
    "fair.water-and-air-show": { onComplete: ["sticker.fair-3"] },
    "fair.smart-machines": { onComplete: ["sticker.fair-4"] },
    "fair.anything-goes": { onComplete: ["sticker.fair-5"] },
    // Creature & Music Machines (M29): the parts each challenge brings to Free Build.
    "creature.hopping-frog": { onComplete: ["part.creature.body", "part.creature.spring-leg"] },
    "creature.flapping-bird": { onComplete: ["part.creature.wing", "part.creature.motor"] },
    "creature.crab-grabber": { onComplete: ["part.creature.leg", "part.creature.claw"] },
    "creature.crawling-bug": { onComplete: ["part.creature.segment"] },
    "creature.spider-walker": { onComplete: ["part.creature.leg"] },
    "creature.dinosaur-walker": { onComplete: ["part.creature.big-leg"] },
    "music.three-note-machine": { onComplete: ["part.music.tone-block"] },
    "music.drum-loop": { onComplete: ["part.music.drum", "part.music.beater"] },
    "music.mechanical-melody": { onComplete: ["part.music.chime"] },
    "music.water-chimes": { onComplete: ["part.music.chime"] },
    "music.robot-band": { onComplete: ["part.music.horn"] },
    "music.grand-workshop-jam": { onComplete: ["part.music.timer"] },
    // Inventor Contracts (M27): the visitor's sticker for either of their jobs.
    "contract.apple-elevator": { onComplete: ["sticker.visitor-chef"] },
    "contract.kitchen-conveyor": { onComplete: ["sticker.visitor-chef"] },
    "contract.roof-beam-lift": { onComplete: ["sticker.visitor-builder"] },
    "contract.site-bridge": { onComplete: ["sticker.visitor-builder"] },
    "contract.hilltop-apples": { onComplete: ["sticker.visitor-farmer"] },
    "contract.water-the-rows": { onComplete: ["sticker.visitor-farmer"] },
    "contract.rescue-line": { onComplete: ["sticker.visitor-firefighter"] },
    "contract.pump-to-the-roof": { onComplete: ["sticker.visitor-firefighter"] },
    "contract.loading-dock": { onComplete: ["sticker.visitor-delivery"] },
    "contract.fragile-parcel": { onComplete: ["sticker.visitor-delivery"] },
    "contract.rover-cargo": { onComplete: ["sticker.visitor-astronaut"] },
    "contract.panel-deployment": { onComplete: ["sticker.visitor-astronaut"] },
    "contract.safe-animal-gate": { onComplete: ["sticker.visitor-zookeeper"] },
    "contract.snack-launcher": { onComplete: ["sticker.visitor-zookeeper"] },
    "contract.treasure-lift": { onComplete: ["sticker.visitor-pirate"] },
    "contract.bell-and-cannon": { onComplete: ["sticker.visitor-pirate"] },
    "contract.stage-lift": { onComplete: ["sticker.visitor-musician"] },
    "contract.beat-machine": { onComplete: ["sticker.visitor-musician"] },
    "contract.fountain-fix": { onComplete: ["sticker.visitor-park"] },
    "contract.ride-starter": { onComplete: ["sticker.visitor-park"] },
    "contract.wheel-wobble": { onComplete: ["sticker.visitor-mechanic"] },
    "contract.generator-test": { onComplete: ["sticker.visitor-mechanic"] },
    "contract.controlled-drop": { onComplete: ["sticker.visitor-scientist"] },
    "contract.sensor-rig": { onComplete: ["sticker.visitor-scientist"] },
    "exp.which-ramp-wins": { onComplete: ["sticker.exp-ramp", "tool.lab-notebook", "avatar.lab-coat"] },
    "exp.grip-test": { onComplete: ["sticker.exp-grip"] },
    "exp.big-gear-vs-small-gear": { onComplete: ["sticker.exp-gear", "badge.fair-tester"] },
    "exp.which-bridge-holds-more": { onComplete: ["sticker.exp-bridge"] },
    "exp.one-battery-or-two": { onComplete: ["sticker.exp-battery"] },
    "exp.which-materials-move": { onComplete: ["sticker.exp-magnet"] },
    "exp.which-pipe-fills-faster": { onComplete: ["sticker.exp-pipe"] },
    "exp.which-wing-flies-farther": { onComplete: ["sticker.exp-wing"] },
    "exp.which-route-is-faster": { onComplete: ["sticker.exp-route"] },
    "exp.bounce-grip-or-slide": { onComplete: ["sticker.exp-bounce", "prop.lab-flask"] },
    "exp.earth-gravity-vs-moon-gravity": { onComplete: ["sticker.exp-gravity"] },
    "grand.ultimate-delivery": { onComplete: ["sticker.grand-ultimate-delivery"] },
    "grand.three-system-rescue": { onComplete: ["sticker.grand-three-system-rescue"] },
    "grand.egg-extreme": { onComplete: ["sticker.grand-egg-extreme"] },
    "grand.power-saving-factory": { onComplete: ["sticker.grand-power-saving-factory"] },
    "grand.magnetic-water-lift": { onComplete: ["sticker.grand-magnetic-water-lift"] },
    "grand.autonomous-bridge": { onComplete: ["sticker.grand-autonomous-bridge"] },
    "grand.flight-robot-relay": { onComplete: ["sticker.grand-flight-robot-relay"] },
    "grand.great-bell-machine": { onComplete: ["sticker.grand-great-bell-machine"] },
    "grand.bolt-rescue": { onComplete: ["sticker.grand-bolt-rescue"] },
    "grand.sprockets-shortcut": { onComplete: ["sticker.grand-sprockets-shortcut"] },
    "grand.giant-chain-reaction": { onComplete: ["sticker.grand-giant-chain-reaction"] },
    "grand.great-wobbleworks-machine": { onComplete: ["badge.campus-restored"] },
    "prototype.reverse-conveyor": { onComplete: ["sticker.proto-reverse-conveyor"] },
    "prototype.super-spring": { onComplete: ["sticker.proto-super-spring"] },
    "prototype.magnet-maze": { onComplete: ["sticker.proto-magnet-maze"] },
    "prototype.worm-gear-box": { onComplete: ["sticker.proto-worm-gear-box"] },
    "prototype.tiny-factory": { onComplete: ["sticker.proto-tiny-factory"] },
    "prototype.no-wheels-allowed": { onComplete: ["sticker.proto-no-wheels-allowed"] },
    "prototype.five-systems": { onComplete: ["sticker.proto-five-systems"] },
    "prototype.sprocket-shortcut": { onComplete: ["sticker.proto-sprocket-shortcut"] },
    "prototype.bubble-lift": { onComplete: ["sprocket.bubble-helmet"] },
    "prototype.upside-down-test": { onComplete: ["bolt.prototype-goggles"] },
    "prototype.maximum-wobble": { onComplete: ["frame.blueprint"] },
    "prototype.bolts-missing-memory": { onComplete: ["bolt.memory-spark", "badge.prototype-lab"] }
});
/** Rewards owed for missions already completed (used when old saves or guest progress move into a profile). */
export function completionRewardIds(levelIds) {
    return [...new Set(levelIds.flatMap(id => MISSION_REWARDS[id]?.onComplete ?? []))].filter(id => rewardById(id) !== undefined);
}
/** Pure reward grant: adds owned + unseen ids and unlocks the matching parts/tools. Returns only the newly added ids. */
export function grantRewardsTo(p, rewardIds) {
    const owned = new Set(p.rewards);
    const added = [...new Set(rewardIds)].filter(id => !owned.has(id) && rewardById(id));
    if (added.length === 0)
        return { profile: p, added };
    const parts = added.filter(id => id.startsWith("part.")).map(id => id.slice("part.".length));
    const tools = added.filter(id => id.startsWith("tool."));
    return { added, profile: { ...p, rewards: [...p.rewards, ...added], unseenRewards: [...new Set([...p.unseenRewards, ...added])], unlockedParts: [...new Set([...p.unlockedParts, ...parts])], unlockedTools: [...new Set([...p.unlockedTools, ...tools])] } };
}
const wild = (min = 3) => ({ kind: "DISCOVERY_COUNT", min, label: `WILD INVENTION — show ${min} science ideas in one TEST` });
const nothingAdded = { kind: "PART_BUDGET", maxPlayerParts: 0, label: "NO EXTRAS — solve it without adding any parts" };
const budget = (n) => ({ kind: "PART_BUDGET", maxPlayerParts: n, label: n === 1 ? "TINY MACHINE — solve it adding just 1 part" : `TINY MACHINE — solve it adding ${n} parts or fewer` });
export const MISSION_STARS = Object.freeze({
    "motion.roll-with-it": { efficient: budget(1), advanced: wild() },
    "motion.ramp-rescue": { efficient: budget(3), advanced: { kind: "DISCOVERY", discoveryId: "motion.friction-grip", label: "PERFECT LANDING — use grip to slow Bolt down" } },
    "motion.too-fast": { efficient: budget(1), advanced: wild() },
    "motion.spring-delivery": { efficient: budget(1), advanced: wild() },
    "motion.slippery-business": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "motion.surface-comparison", label: "SLIP & GRIP — use both surfaces in one run" } },
    "motion.bounce-around": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "motion.bounce", label: "MAXIMUM WOBBLE — bounce on the way" } },
    "motion.heavy-or-light": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "motion.mass-inertia", label: "FAIR TEST — see the same push move light and heavy differently" } },
    "motion.make-it-farther": { efficient: budget(4), advanced: wild() },
    "motion.which-ramp-wins": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "motion.slope-effect", label: "SLOPE SPOTTER — see the slope change the motion" } },
    "motion.duck-cannon": { efficient: budget(1), advanced: wild() },
    "motion.giant-marble-delivery": { efficient: budget(2), advanced: wild(4) },
    "motion.runaway-test-cart": { efficient: budget(1), advanced: wild() },
    "gear.turn-the-door": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "gear.direction-flip", label: "SPIN SPOTTER — watch touching gears turn opposite ways" } },
    "gear.wrong-way-round": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "gear.same-way", label: "DOUBLE FLIP — two flips make the same way" } },
    "gear.speed-it-up": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "gear.speed-up", label: "ZOOM — big gear turns small gear fast" } },
    "gear.slow-and-strong": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "gear.slow-strong", label: "MIGHTY — slow down to get stronger" } },
    "gear.lift-bolt": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "gear.belt-same-way", label: "BELT UP — see a belt keep the direction" } },
    "gear.three-fans": { efficient: budget(4), advanced: { kind: "DISCOVERY", discoveryId: "gear.chain", label: "GEAR TRAIN — pass the turning along" } },
    "gear.clockwork-trouble": { efficient: budget(1), advanced: wild() },
    "gear.conveyor-rescue": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "combo.gear-conveyor", label: "OLD MEETS NEW — gears drive the Motion conveyor" } },
    "gear.big-gear-vs-small-gear": { efficient: budget(4), advanced: { kind: "DISCOVERY", discoveryId: "gear.speed-up", label: "FAIR TEST — measure the fast set-up" } },
    "gear.spin-sprocket": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "gear.slow-strong", label: "SMOOTH RIDE — slow the motor down" } },
    "gear.the-clockwork-carnival": { efficient: budget(6), advanced: wild(4) },
    "gear.jammed-factory-drive": { efficient: budget(2), advanced: wild() },
    "builder.bridge-the-gap": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "structure.load-path", label: "LOAD PATH — carry Bolt's weight to the ground" } },
    "builder.stop-the-wobble": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "structure.triangle", label: "TRIANGLE — keep a triangle steady under load" } },
    "builder.triangle-power": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "structure.bracing", label: "BEFORE & AFTER — TEST it wobbly, then braced" } },
    "builder.heavy-delivery": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "combo.ramp-bridge", label: "UP AND OVER — ramp then bridge" } },
    "builder.build-a-crane": { efficient: budget(4), advanced: { kind: "DISCOVERY", discoveryId: "combo.crane", label: "CRANE — a tower holding a gear winch" } },
    "builder.roof-rescue": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "structure.tension-compression", label: "PULL & PUSH — see parts pulled and squashed" } },
    "builder.tallest-tower": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "structure.triangle", label: "STEADY TOWER — triangles in the wind" } },
    "builder.keep-the-egg-safe": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "structure.soft-landing", label: "SAFETY NET — catch it softly" } },
    "builder.which-bridge-holds-more": { efficient: budget(6), advanced: { kind: "DISCOVERY", discoveryId: "structure.span", label: "FAIR TEST — see a plain beam bend and break" } },
    "builder.elephant-robot-parade": { efficient: budget(4), advanced: { kind: "DISCOVERY", discoveryId: "structure.material", label: "HEAVY DUTY — metal where wood would break" } },
    "builder.the-robot-parade-bridge": { efficient: budget(7), advanced: wild(4) },
    "builder.collapsing-workshop-roof": { efficient: budget(6), advanced: wild() },
    "power.light-it-up": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "power.complete-circuit", label: "LOOP SPOTTER — keep the bulb lit" } },
    "power.broken-loop": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "power.easy-path", label: "SHORTCUT SPOTTER — see electricity skip past a bulb" } },
    "power.push-the-button": { efficient: budget(3), advanced: { kind: "DISCOVERY", discoveryId: "power.switch-control", label: "IN CONTROL — the button switches it on and off" } },
    "power.motor-power": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "combo.power-conveyor", label: "OLD MEETS NEW — electricity drives the Motion conveyor" } },
    "power.two-lights": { efficient: budget(3), advanced: { kind: "DISCOVERY", discoveryId: "power.series", label: "SHARE THE PUSH — light both in one loop" } },
    "power.which-path": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "power.parallel", label: "A PATH EACH — both bulbs bright" } },
    "power.power-the-lift": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "combo.power-gears", label: "MOTOR + GEARS — electric winch" } },
    "power.save-the-battery": { efficient: nothingAdded, advanced: wild(2) },
    "power.one-battery-or-two": { efficient: budget(4), advanced: { kind: "DISCOVERY", discoveryId: "power.more-batteries", label: "DOUBLE PUSH — two batteries, brighter bulb" } },
    "power.buzz-the-duck": { efficient: budget(5), advanced: { kind: "DISCOVERY", discoveryId: "secret.power-duck-alarm", label: "QUACK ATTACK — the duck sets it off" } },
    "power.restore-the-power-grid": { efficient: budget(8), advanced: wild(3) },
    "power.blackout": { efficient: nothingAdded, advanced: wild(2) },
    "magnet.pull-it-in": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "magnet.unlike-attract", label: "OPPOSITES ATTRACT — N meets S" } },
    "magnet.push-it-away": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "magnet.like-repel", label: "SAME ENDS — push it with a matching pole" } },
    "magnet.metal-only": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "magnet.materials", label: "PICKY MAGNET — metal moves, the rest stays" } },
    "magnet.no-touching": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "magnet.no-contact", label: "HANDS OFF — magnetic force only" } },
    "magnet.scrap-sorter": { efficient: budget(3), advanced: { kind: "DISCOVERY", discoveryId: "combo.magnet-conveyor", label: "OLD MEETS NEW — magnet + Motion conveyor" } },
    "magnet.magnet-transport": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "magnet.no-contact", label: "INVISIBLE ROPE — carried without touching" } },
    "magnet.floating-trick": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "magnet.float", label: "FLOAT — repulsion holds it up" } },
    "magnet.electromagnet-crane": { efficient: budget(3), advanced: { kind: "DISCOVERY", discoveryId: "combo.magnet-circuit", label: "GRAB & DROP — electricity on, then off" } },
    "magnet.which-materials-move": { efficient: budget(3), advanced: { kind: "DISCOVERY", discoveryId: "magnet.not-all-metal", label: "NOT EVERY METAL — find the ones that don't move" } },
    "magnet.magnetic-sandwich": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "secret.magnet-sandwich", label: "DOUBLE DECKER — both rings floating" } },
    "magnet.the-giant-scrap-sorter": { efficient: budget(5), advanced: wild(3) },
    "magnet.scrap-avalanche": { efficient: budget(1), advanced: wild(2) },
    "water.fill-the-tank": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "water.path", label: "FOLLOW THE PATH — water goes where pipes lead" } },
    "water.downhill-flow": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "water.climb", label: "TOO HIGH — see that water can't climb on its own" } },
    "water.turn-the-valve": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "water.valve", label: "OPEN & SHUT — one valve open, one closed" } },
    "water.stop-the-leak": { efficient: budget(1), advanced: wild(2) },
    "water.water-the-garden": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "water.jet", label: "SPRAY — jets landing on the beds" } },
    "water.spin-the-wheel": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "combo.water-gears", label: "OLD MEETS NEW — water turns the old fan" } },
    "water.pump-it-up": { efficient: budget(4), advanced: { kind: "DISCOVERY", discoveryId: "water.pump", label: "UPHILL — pump it higher" } },
    "water.spray-the-target": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "water.jet", label: "ARC — hit a target with a jet" } },
    "water.which-pipe-fills-faster": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "water.narrow", label: "FAIR RACE — wide against narrow" } },
    "water.duck-water-park": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "secret.water-duck-splash", label: "SPLASHDOWN — the duck reaches the pool" } },
    "water.the-grand-fountain": { efficient: budget(4), advanced: wild(3) },
    "water.flooded-workshop": { efficient: budget(3), advanced: wild(2) },
    "flight.blow-it-over": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "flight.wind", label: "BREEZE — moving air pushes" } },
    "flight.long-glide": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "flight.stability", label: "STEADY — tail keeps it level" } },
    "flight.safe-landing": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "flight.parachute", label: "SOFT — catch the air" } },
    "flight.balloon-lift": { efficient: budget(3), advanced: { kind: "DISCOVERY", discoveryId: "flight.buoyancy", label: "FLOAT — push beats weight" } },
    "flight.through-the-hoops": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "combo.flight-spring", label: "OLD MEETS NEW — spring launch" } },
    "flight.balance-the-wings": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "flight.stability", label: "BALANCED — fly without flipping" } },
    "flight.propeller-push": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "flight.thrust-lift", label: "PUSH & LIFT — two different jobs" } },
    "flight.cross-the-canyon": { efficient: budget(4), advanced: { kind: "DISCOVERY", discoveryId: "combo.flight-battery", label: "GLIDE HOME — battery out, wings on" } },
    "flight.which-wing-flies-farther": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "flight.lift", label: "LIFT — see wings hold it up" } },
    "flight.flying-sprocket": { efficient: budget(4), advanced: { kind: "DISCOVERY", discoveryId: "secret.flight-sprocket", label: "SKY PUPPY — through a hoop" } },
    "flight.the-canyon-flyer": { efficient: budget(4), advanced: wild(3) },
    "flight.falling-cargo": { efficient: budget(2), advanced: wild(2) },
    "robot.move-forward": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "robot.literal", label: "TOO FAR — see the robot do exactly what it's told" } },
    "robot.turn-the-corner": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "robot.sequence", label: "IN ORDER — drive, turn, drive" } },
    "robot.wait-for-it": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "robot.timing", label: "PERFECT TIMING — wait, then go" } },
    "robot.avoid-the-wall": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "robot.condition", label: "SMART RULE — IF wall, turn; ELSE go" } },
    "robot.follow-the-colour": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "combo.robot-conveyor", label: "OLD MEETS NEW — start the old conveyor" } },
    "robot.press-the-button": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "robot.actuator", label: "PRESS — use the pusher" } },
    "robot.carry-the-box": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "robot.actuator", label: "GRIPPER — grab and drop" } },
    "robot.factory-robot": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "combo.robot-factory", label: "PACKED — the machine packs a box" } },
    "robot.which-route-is-faster": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "robot.sequence", label: "TWO PROGRAMS — race them" } },
    "robot.robot-dance-party": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "secret.robot-dance", label: "DISCO — six beats" } },
    "robot.automated-factory": { efficient: nothingAdded, advanced: wild(3) },
    "robot.robot-traffic-jam": { efficient: nothingAdded, advanced: wild(2) },
    "space.build-the-rover": { efficient: budget(4), advanced: { kind: "DISCOVERY", discoveryId: "space.rover", label: "ROVER — it drives itself" } },
    "space.cross-the-crater": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "space.grip", label: "GRIP — climb the steep rim" } },
    "space.launch-straight": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "space.fins", label: "STEADY — straight through the gust" } },
    "space.reach-the-target": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "space.trajectory", label: "LONG SHOT — lean and land far away" } },
    "space.safe-touchdown": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "space.no-air", label: "NO AIR — find out why a parachute won't help" } },
    "space.satellite-power": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "space.solar", label: "SUNNY — face the sun" } },
    "space.robot-arm-repair": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "combo.space-robot-power", label: "REPAIRED — the radio comes back" } },
    "space.moon-base-delivery": { efficient: budget(3), advanced: { kind: "DISCOVERY", discoveryId: "space.solar", label: "SOLAR ROVER — powered by the Sun" } },
    "space.earth-gravity-vs-moon-gravity": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "space.mass-same", label: "FAIR TEST — mass stays the same" } },
    "space.space-duck": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "secret.space-duck", label: "ORBIT — round the planet" } },
    "space.the-wobbleworks-explorer": { efficient: budget(4), advanced: wild(3) },
    "space.broken-launch-tower": { efficient: budget(2), advanced: wild(2) },
    "chain.first-domino": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "chain.cause-effect", label: "ONE PUSH — five real steps" } },
    "chain.bell-ringer": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "chain.cause-effect", label: "ONE PUSH — every bell" } },
    "chain.up-down-around": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "chain.cause-effect", label: "ONE PUSH — roll, lift, spin" } },
    "chain.power-change": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "chain.energy-transfer", label: "PASS IT ON — energy changes kind" } },
    "chain.wet-and-wild": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "secret.chain-duck", label: "FINALE — duck through the confetti" } },
    "chain.magnetic-middle": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "chain.many-systems", label: "MIX — three kinds of machine" } },
    "chain.robot-relay": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "secret.chain-duck", label: "FINALE — duck through the confetti" } },
    "chain.air-mail": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "chain.energy-transfer", label: "PASS IT ON — by air" } },
    "chain.three-domains": { efficient: budget(1), advanced: { kind: "DISCOVERY", discoveryId: "chain.many-systems", label: "MIX — three kinds of machine" } },
    "chain.no-repeats": { efficient: budget(1), advanced: wild(2) },
    "chain.long-haul": { efficient: nothingAdded, advanced: { kind: "DISCOVERY", discoveryId: "secret.chain-marathon", label: "MARATHON — twenty seconds" } },
    "chain.duck-finale": { efficient: budget(2), advanced: { kind: "DISCOVERY", discoveryId: "chain.long-chain", label: "LONG CHAIN — fifteen steps" } },
    ...Object.fromEntries(["exp.which-ramp-wins", "exp.grip-test", "exp.big-gear-vs-small-gear", "exp.which-bridge-holds-more", "exp.one-battery-or-two", "exp.which-materials-move", "exp.which-pipe-fills-faster", "exp.which-wing-flies-farther", "exp.which-route-is-faster", "exp.bounce-grip-or-slide", "exp.earth-gravity-vs-moon-gravity"].map(id => [id, { efficient: { kind: "DISCOVERY", discoveryId: "experiment.prediction", label: "GOOD GUESS — your prediction matched the result" }, advanced: { kind: "DISCOVERY", discoveryId: "experiment.change-one", label: "CHANGE ONE THING — then test again" } }]))
});
export function evaluateStars(levelId, evidence) {
    const stars = ["solve"];
    const goals = MISSION_STARS[levelId];
    if (!goals)
        return stars;
    if (goalMet(goals.efficient, evidence))
        stars.push("efficient");
    if (goalMet(goals.advanced, evidence))
        stars.push("advanced");
    return stars;
}
export function goalMet(goal, evidence) {
    if (goal.kind === "PART_BUDGET")
        return evidence.playerPartCount <= goal.maxPlayerParts;
    if (goal.kind === "DISCOVERY_COUNT")
        return new Set(evidence.discoveries).size >= goal.min;
    return evidence.discoveries.includes(goal.discoveryId);
}
